force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <description>Successfully done trades/exchanges</description>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <label>Date Booked</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TradesControllerTest.cls
@IsTest
public with sharing class TradesControllerTest {
    @TestSetup 
    static void setup() {
        List<Trade__c> trades = new List<Trade__c>();
        for(Integer i = 0; i < 200; i++) {
            trades.add(new Trade__c(Buy_Currency__c='USD', Buy_Amount__c=100, Sell_Currency__c='EUR', Sell_Amount__c=89, Rate__c = 1.09, Date_Booked__c = Datetime.now()));
        }
        insert trades;
    }

    @IsTest
    static void getLatestRates() {
        String currencies = 'GBP,EUR,USD';
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ApiMockResponse());
        String result = TradesController.getLatestRates(currencies);
        Test.stopTest();

        Boolean isSuccess = false;
        JSONParser parser = JSON.createParser(result);
        while (parser.nextToken() != null) {
            if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && 
                (parser.getText() == 'success')) {
                parser.nextToken();
                isSuccess = parser.getBooleanValue();
                break;
            }
        }
        System.assertEquals(isSuccess, true);
    }    

    @IsTest
    static void getTrades25() {
        List<Trade__c> trades = new List<Trade__c>();

        Test.startTest();
        trades = TradesController.getTrades(25, 0);
        Test.stopTest();

        System.assertEquals(trades.size(), 25);
    }  

    @IsTest
    static void getTrades125() {
        List<Trade__c> trades = new List<Trade__c>();

        Test.startTest();
        trades = TradesController.getTrades(125, 75);
        Test.stopTest();

        System.assertEquals(trades.size(), 125);
    }  

    @IsTest
    static void getTradesToManyRequested() {
        List<Trade__c> trades = new List<Trade__c>();

        Test.startTest();
        trades = TradesController.getTrades(225, 0);
        Test.stopTest();

        System.assertEquals(trades.size(), 200);
        System.assertNotEquals(trades.size(), 225);
    }  
}